# Github actons part 1 by Anton Dvornikov

name: first-actions

on:
  push:
    branches: [ master ]

jobs:
  testing:

    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing"
      

  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Deploy"